[include]

[misc]
pre_sudo = true
disable = [
    "firmware",
    "snap",
    "chezmoi",
]
last = [
    "flatpak",
]
ignore_failures = [
    "pip3",
    "antigravity",
]
cleanup = true
notify_end = "on_failure"
ssh_arguments = "-o ConnectTimeout=2"

[pre_commands]
# "Backup dotfiles" = "chezmoi git -- push"

[post_commands]
# "Reload shell" = "exec $SHELL"  # no-op: runs in a subprocess, doesn't affect your interactive shell

[commands]
# "Update Python env" = "~/dev/.venv/bin/pip install -U pip"

[python]
enable_pip_review = true

[linux]
arch_package_manager = "paru"
yay_arguments = "--nodevel"

[git]
repos = [
  # "~/dotfiles",
  # "~/src/*/",  # uncomment when you have git repos here
]
max_concurrency = 5
arguments = "--rebase --autostash"

[firmware]
upgrade = false

[flatpak]
use_sudo = true

[vscode]

[cargo]

[rustup]

[containers]
#ignored_containers = ["odysseus-odysseus"]
